### PR TITLE
Update example in ReadMe to reflect renamed package

### PR DESCRIPTION
**Pull request by serenahathi**
**PR Summary**
- This PR updates the example in the ReadMe to reflect the renamed package

### CODE REVIEW

**Comment by serenahathi** [comment]
@unsign3d  Does the patch version also need to be updated for this change?  Saw this in the [semantic version specification](https://semver.org/#spec-item-3) so wanted to double check:

```Once a versioned package has been released, the contents of that version MUST NOT be modified. Any modifications MUST be released as a new version.```

**Comment by unsign3d** [comment]
I would say that for this specific case it's not a problem

**Comment by unsign3d** [comment]
but ideally yes

**Comment by serenahathi** [comment]
I have updated the patch version.  Reading this repo's contribution [guidelines](I have updated the patch version.  According to your contribution guidelines, only a Codeowner can merge so over to you 😄 ), only a Codeowner can merge so over to you 😄

**Comment by unsign3d** [comment]
o.o you're the owner team, I need to check how to give you permission XD

**Comment by serenahathi** [comment]
> o.o you're the owner team, I need to check how to give you permission XD

I was technically able to press merge but I saw that  @babbel/babbel-oss have been defined as Codeowners here https://github.com/babbel/miza-kinesis/blob/master/CODEOWNERS so wasn't sure!

**Comment by unsign3d** [comment]
ah no, you're the code owner, the idea of the @babbel/oss is that in case we are filtering before it comes to you

**Comment by unsign3d** [comment]
or you can just ping in case of doubt

**Comment by serenahathi** [comment]
Ah I see - good to know!

**Comment by unsign3d** [comment]
I will try to find a more sensible way to handle it XD

**Pull request merged**
